render: renderer.o raster.o model.o 
	cc68x -g renderer.o raster.o model.o -o render
	
tst_rast: tst_rast.o raster.o
	cc68x -g tst_rast.o raster.o -o tst_rast

tst_rast.o: tst_rast.c raster.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c

clean: 
	$(RM) *.o
