flappy: flappy_bird.o input.o renderer.o raster.o events.o model.o bitmaps.o
	cc68x -g main\flappy.o main\input.o renderer\renderer.o raster\raster.o events\events.o model.o bitmaps.o -o flappy

tst_all: tst_ren tst_rast tst_evnt

tst_ren: tst_ren.o renderer.o raster.o model.o bitmaps.o
	cc68x -g tst_ren.o renderer\renderer.o raster\raster.o model.o bitmaps.o -o tst_ren

tst_rast: tst_rast.o raster.o
	cc68x -g tst_rast.o raster\raster.o -o tst_rast

tst_evnt: tst_evnt.o events.o model.o
	cc68x -g tst_evnt.o events\events.o model.o -o tst_evnt

tst_ren.o: tst_ren.c renderer\renderer.h
	cc68x -g -c tst_ren.c	

tst_rast.o: tst_rast.c raster\raster.h
	cc68x -g -c tst_rast.c

tst_evnt.o: tst_evnt.c events\events.h
	cc68x -g -c tst_evnt.c

events.o: events\events.c events\events.h
	cc68x -g -c events\events.c

raster.o: raster\raster.c raster\raster.h
	cc68x -g -c raster\raster.c

model.o: model.c model.h
	cc68x -g -c model.c

renderer.o: renderer\renderer.c renderer\renderer.h
	cc68x -g -c renderer\renderer.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

flappy_bird.o: main\flappy.c renderer\renderer.h raster\raster.h events\events.h model.h bitmaps.h
	cc68x -g -c main\flappy.c

input.o: main\input.c main\input.h
	cc68x -g -c main\input.c

clean: 
	$(RM) *.o renderer\*.o raster\*.o  events\*.o main\*.o
