/*------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Team Members: Rami Mikha & Jarod Dacocos

The data structures in this file represent the game's
objects - the bird, the pipe and their properties. The 
functions in this file represent the objects behaviours such as
movement of pipe and bird as well as collisions between the bird
and the pipe or ground.
------------------------------------------------------------*/ 

#ifndef MODEL_H
#define MODEL_H

#define BIRD_WIDTH 32
#define BIRD_HEIGHT 32
#define PIPE_WIDTH 32
#define PIPE_HEIGHT 640
#define PIPE_OPENING_SIZE 96
#define PIPE_SECTION_HEIGHT 32
#define GROUND_Y1 300
#define GROUND_Y2 400
#define GROUND_X1 0
#define GROUND_X2 640
#define SCORE_Y 60
#define SCORE_X 10
#define SCORE_WIDTH 24
#define FONT_LENGTH 7

#define SCORE_TITLE_Y 50
#define SCORE_TITLE_X 10

typedef struct {
  unsigned int x,y,prev_y;
  int delta_y;
} Bird;

typedef struct {
  unsigned int x,y,prev_x;
  unsigned int opening_height;
  int delta_x;
} Pipes;

typedef struct {
   int value;
   int prev_value;
} Score;


typedef struct {
  Bird bird;
  Pipes pipe;
  Score score;
} Model;


/*------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Function Name: move_bird                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Purpose:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   Moves the bird object vertically by a specified amount.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Inputs: 
   bird - pointer to the bird object to be moved
   move_value - amount of which the bird moves vertically
------------------------------------------------------------*/

void move_bird (Bird *bird, int move_value);

/*------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Function Name: move_pipe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Purpose:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   Move the pipe object horizontally by a specified amount.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Inputs: 
   pipe - pointer to the pipe object to be moved
   move_value - amount of which the pipes moves horizontally
------------------------------------------------------------*/

void move_pipe (Pipes *pipe, int move_value);

/*------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Function Name: check_collision                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Purpose:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   Checks for collisions between the bird and a pipe or the bird
   and the ground.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Inputs: 
   bird - pointer to the bird object
   pipe - pointer to the pipe object

Outputs:
   collision_bool - flag that returns '1' if collision is detected
                    otherwise returns '0'.
------------------------------------------------------------*/

int check_collision (Bird *bird, Pipes *pipe);

void increment_score(Bird *bird, Pipes *pipe, Score *score);

#endif
