tst_events: tst_events.o events.o
	cc68x -g tst_events.o events.o -o tst_events

tst_events.o: tst_events.c events.h
	cc68x -g -c tst_events.c

events.o: events.c events.h
	cc68x -g -c events.c

clean: 
	$(RM) *.o
